IF(UNIX)
  INCLUDE(GNUInstallDirs)
  MESSAGE(STATUS "Searching for g2o ...")

  SET(G2O_SEARCH_PATHS
    /usr/local
    /usr
    ${CMAKE_PREFIX_PATH})

  SET(G2O_LIBRARY_PATH_SUFFIXES
    ${CMAKE_INSTALL_LIBDIR}
    lib
    lib64)

  IF(CMAKE_LIBRARY_ARCHITECTURE)
    LIST(APPEND G2O_LIBRARY_PATH_SUFFIXES
      lib/${CMAKE_LIBRARY_ARCHITECTURE}
      ${CMAKE_INSTALL_LIBDIR}/${CMAKE_LIBRARY_ARCHITECTURE})
  ENDIF()

  LIST(REMOVE_DUPLICATES G2O_LIBRARY_PATH_SUFFIXES)

  FIND_PATH(G2O_INCLUDE_DIR
    NAMES g2o/core/base_vertex.h
    PATHS ${G2O_SEARCH_PATHS}
    PATH_SUFFIXES include)
  IF (G2O_INCLUDE_DIR)
    MESSAGE(STATUS "Found g2o headers in: ${G2O_INCLUDE_DIR}")
  ENDIF ()

  FIND_LIBRARY(G2O_CORE_LIB
    NAMES g2o_core g2o_core_rd
    PATHS ${G2O_SEARCH_PATHS}
    PATH_SUFFIXES ${G2O_LIBRARY_PATH_SUFFIXES})
  FIND_LIBRARY(G2O_STUFF_LIB
    NAMES g2o_stuff g2o_stuff_rd
    PATHS ${G2O_SEARCH_PATHS}
    PATH_SUFFIXES ${G2O_LIBRARY_PATH_SUFFIXES})
  FIND_LIBRARY(G2O_TYPES_SLAM2D_LIB
    NAMES g2o_types_slam2d g2o_types_slam2d_rd
    PATHS ${G2O_SEARCH_PATHS}
    PATH_SUFFIXES ${G2O_LIBRARY_PATH_SUFFIXES})
  FIND_LIBRARY(G2O_TYPES_SLAM3D_LIB
    NAMES g2o_types_slam3d g2o_types_slam3d_rd
    PATHS ${G2O_SEARCH_PATHS}
    PATH_SUFFIXES ${G2O_LIBRARY_PATH_SUFFIXES})
  FIND_LIBRARY(G2O_SOLVER_CHOLMOD_LIB
    NAMES g2o_solver_cholmod g2o_solver_cholmod_rd
    PATHS ${G2O_SEARCH_PATHS}
    PATH_SUFFIXES ${G2O_LIBRARY_PATH_SUFFIXES})
  FIND_LIBRARY(G2O_SOLVER_PCG_LIB
    NAMES g2o_solver_pcg g2o_solver_pcg_rd
    PATHS ${G2O_SEARCH_PATHS}
    PATH_SUFFIXES ${G2O_LIBRARY_PATH_SUFFIXES})
  FIND_LIBRARY(G2O_SOLVER_CSPARSE_LIB
    NAMES g2o_solver_csparse g2o_solver_csparse_rd
    PATHS ${G2O_SEARCH_PATHS}
    PATH_SUFFIXES ${G2O_LIBRARY_PATH_SUFFIXES})
  FIND_LIBRARY(G2O_SOLVER_EIGEN_LIB
    NAMES g2o_solver_eigen g2o_solver_eigen_rd
    PATHS ${G2O_SEARCH_PATHS}
    PATH_SUFFIXES ${G2O_LIBRARY_PATH_SUFFIXES})
  FIND_LIBRARY(G2O_INCREMENTAL_LIB
    NAMES g2o_incremental g2o_incremental_rd
    PATHS ${G2O_SEARCH_PATHS}
    PATH_SUFFIXES ${G2O_LIBRARY_PATH_SUFFIXES})
  FIND_LIBRARY(G2O_CSPARSE_EXTENSION_LIB
    NAMES g2o_csparse_extension g2o_csparse_extension_rd
    PATHS ${G2O_SEARCH_PATHS}
    PATH_SUFFIXES ${G2O_LIBRARY_PATH_SUFFIXES})

  SET(G2O_LIBRARIES ${G2O_CSPARSE_EXTENSION_LIB}
                    ${G2O_CORE_LIB}
                    ${G2O_STUFF_LIB}
                    ${G2O_TYPES_SLAM2D_LIB}
                    ${G2O_TYPES_SLAM3D_LIB}
                    ${G2O_SOLVER_CHOLMOD_LIB}
                    ${G2O_SOLVER_PCG_LIB}
                    ${G2O_SOLVER_CSPARSE_LIB}
                    ${G2O_SOLVER_EIGEN_LIB})

  IF(G2O_INCREMENTAL_LIB)
    LIST(APPEND G2O_LIBRARIES ${G2O_INCREMENTAL_LIB})
  ENDIF()

  SET(G2O_REQUIRED_LIBRARIES
    G2O_CSPARSE_EXTENSION_LIB
    G2O_CORE_LIB
    G2O_STUFF_LIB
    G2O_TYPES_SLAM2D_LIB
    G2O_TYPES_SLAM3D_LIB
    G2O_SOLVER_CHOLMOD_LIB
    G2O_SOLVER_PCG_LIB
    G2O_SOLVER_CSPARSE_LIB
    G2O_SOLVER_EIGEN_LIB)

  FOREACH(G2O_REQUIRED_LIBRARY ${G2O_REQUIRED_LIBRARIES})
    IF(NOT ${G2O_REQUIRED_LIBRARY})
      LIST(APPEND G2O_MISSING_LIBRARIES ${G2O_REQUIRED_LIBRARY})
    ENDIF()
  ENDFOREACH()

  IF(NOT G2O_MISSING_LIBRARIES AND G2O_INCLUDE_DIR)
    SET(G2O_FOUND "YES")
    MESSAGE(STATUS "Found libg2o: ${G2O_LIBRARIES}")
  ELSE()
    IF(G2O_MISSING_LIBRARIES)
      message(FATAL_ERROR "Could not find libg2o libraries: ${G2O_MISSING_LIBRARIES}")
    ENDIF()
    IF(NOT G2O_INCLUDE_DIR)
      message(FATAL_ERROR "Could not find g2o include directory!")
    ENDIF()
  ENDIF()
ENDIF(UNIX)
